dict_lunch_default={'Lunedì': {'Colazione': {'Latte': {'Quantità': 200, 'Unità': 'ml'}, 'Biscotti integrali': {'Quantità': 4, 'Unità': 'pz'}, 'Marmellata': {'Quantità': 40, 'Unità': 'g'}, 'Frutto': {'Quantità': 1, 'Unità': 'pz'}}, 'Pranzo': {'Fagioli': {'Quantità': 80, 'Unità': 'g'}, 'Pane integrale': {'Quantità': 60, 'Unità': 'g'}, 'Verdura': {'Quantità': 200, 'Unità': 'g'}}, 'Cena': {'Merluzzo o nasello fresco': {'Quantità': 200, 'Unità': 'g'}, 'Verdura': {'Quantità': 200, 'Unità': 'g'}, 'Ortaggi': {'Quantità': 100, 'Unità': 'g'}, 'Piadina': {'Quantità': 55, 'Unità': 'g'}}, 'SpuntinoMattina': {'Frutto': {'Quantità': 1, 'Unità': 'pz'}, 'Mandorle/Nocciole': {'Quantità': 4, 'Unità': 'pz'}}, 'SpuntinoPomeriggio': {'Pane integrale': {'Quantità': 50, 'Unità': 'g'}, 'Fesa di tacchino': {'Quantità': 50, 'Unità': 'g'}}}, 'Martedì': {'Colazione': {'Yogurt Greco': {'Quantità': 170, 'Unità': 'g'}, 'Cereali Integrali': {'Quantità': 50, 'Unità': 'g'}, 'Frutto': {'Quantità': 1, 'Unità': 'pz'}}, 'Pranzo': {'Farro': {'Quantità': 70, 'Unità': 'g'}, 'Verdura': {'Quantità': 200, 'Unità': 'g'}, 'Uova': {'Quantità': 2, 'Unità': 'pz'}}, 'Cena': {'Petto di pollo': {'Quantità': 200, 'Unità': 'g'}}, 'SpuntinoMattina': {'Frutto': {'Quantità': 1, 'Unità': 'pz'}}, 'SpuntinoPomeriggio': {'Pomodori': {'Quantità': 50, 'Unità': 'g'}}}, 'Mercoledì': {'Colazione': {'Succo di frutta': {'Quantità': 200, 'Unità': 'ml'}, 'Pane integrale': {'Quantità': 50, 'Unità': 'g'}, 'Prosciutto crudo': {'Quantità': 40, 'Unità': 'g'}}, 'Pranzo': {'Cous cous': {'Quantità': 70, 'Unità': 'g'}, 'Tonno al naturale': {'Quantità': 120, 'Unità': 'g'}, 'Verdura': {'Quantità': 200, 'Unità': 'g'}}, 'Cena': {'Ricotta di mucca': {'Quantità': 120, 'Unità': 'g'}, 'Verdure': {'Quantità': 200, 'Unità': 'g'}, 'Ortaggi': {'Quantità': 100, 'Unità': 'g'}, 'Piadina': {'Quantità': 55, 'Unità': 'g'}}, 'SpuntinoMattina': {'Frutto': {'Quantità': 1, 'Unità': 'pz'}}, 'SpuntinoPomeriggio': {'Pane integrale': {'Quantità': 50, 'Unità': 'g'}, 'Pomodori': {'Quantità': 5, 'Unità': 'pz'}}}, 'Giovedì': {'Colazione': {'Yogurt Greco': {'Quantità': 170, 'Unità': 'g'}, 'Biscotti secchi': {'Quantità': 7, 'Unità': 'pz'}, 'Marmellata': {'Quantità': 50, 'Unità': 'g'}}, 'Pranzo': {'Patate': {'Quantità': 300, 'Unità': 'g'}, 'Seppia': {'Quantità': 200, 'Unità': 'g'}, 'Verdura': {'Quantità': 200, 'Unità': 'g'}}, 'Cena': {'Bresaola': {'Quantità': 100, 'Unità': 'g'}, 'Verdure': {'Quantità': 200, 'Unità': 'g'}, 'Ortaggi': {'Quantità': 100, 'Unità': 'g'}, 'Piadina': {'Quantità': 55, 'Unità': 'g'}}, 'SpuntinoMattina': {'Frutto': {'Quantità': 1, 'Unità': 'pz'}, 'Mandorle/Nocciole': {'Quantità': 5, 'Unità': 'pz'}}, 'SpuntinoPomeriggio': {'Pane integrale': {'Quantità': 50, 'Unità': 'g'}, 'Pomodori': {'Quantità': 5, 'Unità': 'pz'}}}, 'Venerdì': {'Colazione': {'Latte': {'Quantità': 200, 'Unità': 'ml'}, 'Biscotti integrali': {'Quantità': 4, 'Unità': 'pz'}, 'Marmellata': {'Quantità': 40, 'Unità': 'g'}, 'Frutto': {'Quantità': 1, 'Unità': 'pz'}}, 'Pranzo': {'Pasta integrale': {'Quantità': 60, 'Unità': 'g'}, 'Fagioli': {'Quantità': 50, 'Unità': 'g'}, 'Fesa di tacchino': {'Quantità': 50, 'Unità': 'g'}, 'Verdura': {'Quantità': 200, 'Unità': 'g'}}, 'Cena': {'Uova': {'Quantità': 2, 'Unità': 'pz'}, 'Verdura': {'Quantità': 200, 'Unità': 'pz'}, 'Ortaggi': {'Quantità': 100, 'Unità': 'pz'}, 'Piadina': {'Quantità': 55, 'Unità': 'pz'}}, 'SpuntinoMattina': {'Frutto': {'Quantità': 1, 'Unità': 'pz'}, 'Mandorle/Nocciole': {'Quantità': 9, 'Unità': 'pz'}}, 'SpuntinoPomeriggio': {'Pane integrale': {'Quantità': 50, 'Unità': 'g'}, 'Pomodori': {'Quantità': 1, 'Unità': 'pz'}}}, 'Sabato': {'Colazione': {'Yogurt Greco': {'Quantità': 170, 'Unità': 'g'}, 'Cereali Integrali': {'Quantità': 50, 'Unità': 'g'}, 'Frutto': {'Quantità': 1, 'Unità': 'pz'}}, 'Pranzo': {'Petto di pollo': {'Quantità': 220, 'Unità': 'g'}, 'Verdure': {'Quantità': 200, 'Unità': 'g'}, 'Pane integrale': {'Quantità': 60, 'Unità': 'g'}}, 'Cena': {'Pizza Margherita': {'Quantità': 1, 'Unità': 'pz'}}, 'SpuntinoMattina': {'Mandorle/Nocciole': {'Quantità': 9, 'Unità': 'pz'}}, 'SpuntinoPomeriggio': {'Yogurt': {'Quantità': 125, 'Unità': 'g'}}}, 'Domenica': {'Colazione': {'Succo di frutta': {'Quantità': 200, 'Unità': 'ml'}, 'Pane integrale': {'Quantità': 50, 'Unità': 'g'}, 'Prosciutto crudo': {'Quantità': 40, 'Unità': 'g'}}, 'Pranzo': {'Pasta integrale': {'Quantità': 80, 'Unità': 'pz'}, 'Filetto magro di bovino adulto': {'Quantità': 150, 'Unità': 'pz'}, 'Verdura': {'Quantità': 200, 'Unità': 'pz'}}, 'Cena': {'Salmone fresco': {'Quantità': 200, 'Unità': 'g'}, 'Verdura': {'Quantità': 200, 'Unità': 'g'}, 'Ortaggi': {'Quantità': 100, 'Unità': 'g'}, 'Piadina': {'Quantità': 100, 'Unità': 'g'}}, 'SpuntinoMattina': {'Yogurt': {'Quantità': 1, 'Unità': 'pz'}, 'Crackers integrali': {'Quantità': 1, 'Unità': 'pz'}}, 'SpuntinoPomeriggio': {'Yogurt': {'Quantità': 1, 'Unità': 'pz'}, 'Crackers integrali': {'Quantità': 5, 'Unità': 'pz'}}}}

list_of_days = ['Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato', 'Domenica']
list_of_meals = ["Colazione", "Pranzo", "Cena", "SpuntinoMattina","SpuntinoPomeriggio"]
# dict_giorni={
# 'Lunedì':{
#     'Fagioli':80,
#     'Verdure':400,
#     'Frutta':2,
#     'Piadine':55,
#     'Fesa':50,
#     'Merluzzo':200,
#     'Ortaggi':100,
#     'Marmellata':40,
#     'Latte':200,
#     'Fette_Biscottate':50,
#     'Frutta_Secca':4,
#     'Pane':50,
#     'Pasta':60},
# 'Martedì':{
#     'Verdure':400,
#     'Frutta':4,
#     'Piadine':55,
#     'Frutta_Secca':5,
#     'Pane':50,
#     'Cereali':50,
#     'Farro':70,
#     'Pomodori':20,
#     'Yogurt':170,
#     'Pollo':200,
#     'Uova':2},
# 'Mercoledì':{
#     'Verdure':400,
#     'Frutta':3,
#     'Piadine':55,
#     'Ortaggi':100,
#     'Marmellata':50,
#     'Pane':100,
#     'Prosciutto':40,
#     'Succo_di_Frutta':200,
#     'Cous_Cous':70,
#     'Tonno':120,
#     'Ricotta':120
#  },
# 'Giovedì':{
#  'Verdure':400,
#  'Frutta':3,
#  'Piadine':55,
#  'Fesa':150,
#  'Merluzzo':200,
#  'Ortaggi':100,
#  'Marmellata':50,
#  'Frutta_Secca':5,
#  'Pane':50,
#  'Pomodori':20,
#  'Yogurt':170,
#  'Biscotti':50,
#  'Patate':300,
# },
# 'Venerdì':{
#  'Fagioli':50,
#  'Latte':200,
#  'Verdure':400,
#  'Frutta':3,
#  'Piadine':55,
#  'Fesa':50,
#  'Ortaggi':100,
#  'Marmellata':40,
#  'Fette_Biscottate':50,
#  'Frutta_Secca':9,
#  'Pane':50,
#  'Pomodori':20,
#  'Uova':2,
#  'Pasta':60,

# },
# 'Sabato':{
#  'Yogurt':170,
#  'Verdure':200,
#  'Cereali':50,
#  'Frutta':1,
#  'Piadine':55,
#  'Ortaggi':100,
#  'Fette_Biscottate':50,
#  'Frutta_Secca':9,
#  'Pane':60,
#  'Pollo':220,
#  'Yogurt':125
# },
# 'Domenica':{
#  'Succo_di_Frutta':200,
#  'Verdure':400,
#  'Prosciutto':40,
#  'Frutta':2,
#  'Piadine':55,
#  'Ortaggi':100,
#  'Pane':50,
#  'Yogurt':125,
#  'Pasta':80,
#  'Filetto':150,
#  'Salmone':100}
#  }

# dict_lunch_tmp={'Lunedì':{
#     'Colazione':{
#     'Marmellata':40,
#     'Latte':200,
#     'Fette_Biscottate':50,

#     },
#     'Pranzo':{
#     'Fagioli':80,
#     'Verdure':200,
#     'Pane':60,
#     'Frutta':1
#     },
#     'Cena':{
#         'Verdure':200,
#         'Piadine':55,
#         'Merluzzo':200,
#         'Ortaggi':100,
#         'Frutta':1
#     },
#     'SpuntinoMattina':{
#         'Frutta':1,
#         'Frutta_Secca':4
#     },
#     'SpuntinoPomeriggio':{
#         'Pane':50,
#         'Fesa':50
#     }
# },
# 'Martedì':{
#     'Colazione':{
#     'Yogurt':170,
#     'Cereali':50,
#     'Frutta':1

#     },
#     'Pranzo':{
#     'Farro':70,
#     'Verdure':200,
#     'Uova':2,
#     'Frutta':1
#     },
#     'Cena':{
#         'Verdure':200,
#         'Piadine':55,
#         'Pollo':200,
#         'Ortaggi':100,
#         'Frutta':1
#     },
#     'SpuntinoMattina':{
#         'Frutta_Secca':4,
#         'Frutta':1
#     },
#     'SpuntinoPomeriggio':{
#         'Pane':50,
#         'Pomodori':50
#     }
# },
# 'Mercoledì':{
#        'Colazione':{
#     'Succo_di_Frutta':200,
#     'Pane':50,
#     'Prosciutto':40

#     },
#     'Pranzo':{
#     'Cous_Cous':70,
#     'Verdure':200,
#     'Tonno':120,
#     'Frutta':1
#     },
#     'Cena':{
#         'Verdure':200,
#         'Piadine':55,
#         'Ricotta':120,
#         'Ortaggi':100,
#         'Frutta':1
#     },
#     'SpuntinoMattina':{
#         'Frutta':1
#     },
#     'SpuntinoPomeriggio':{
#         'Pane':50,
#         'Pomodori':50
#     }
#  },
# 'Giovedì':{
#           'Colazione':{
#     'Yogurt':170,
#     'Biscotti':50,
#     'Marmellata':50

#     },
#     'Pranzo':{
#     'Patate':300,
#     'Verdure':200,
#     'Merluzzo':200,
#     'Frutta':1
#     },
#     'Cena':{
#         'Verdure':200,
#         'Piadine':55,
#         'Bresaola':100,
#         'Ortaggi':100,
#         'Frutta':1
#     },
#     'SpuntinoMattina':{
#         'Frutta':1,
#         'Frutta_Secca':4
#     },
#     'SpuntinoPomeriggio':{
#         'Pane':50,
#         'Pomodori':50
#     }
# },
# 'Venerdì':{
#     'Colazione':{
#     'Latte':200,
#     'Fette_Biscottate':50,
#     'Marmellata':40

#     },
#     'Pranzo':{
#     'Pasta':60,
#     'Fesa':50,
#     'Verdure':200,
#     'Fagioli':50,
#     'Frutta':1
#     },
#     'Cena':{
#         'Verdure':200,
#         'Piadine':55,
#         'Uova':2,
#         'Ortaggi':100,
#         'Frutta':1
#     },
#     'SpuntinoMattina':{
#         'Frutta':1,
#         'Frutta_Secca':9
#     },
#     'SpuntinoPomeriggio':{
#         'Pane':50,
#         'Pomodori':50
#     }
# },
# 'Sabato':{
#     'Colazione':{
#     'Yogurt':170,
#     'Cereali':50,
#     'Frutta':1

#     },
#     'Pranzo':{
#     'Pollo':220,
#     'Verdure':200,
#     'Pane':60,
#     },
#     'Cena':{
#         'Verdure':200,
#         'Piadine':55,
#         'Ricotta':120,
#         'Ortaggi':100,
#         'Frutta':1
#     },
#     'SpuntinoMattina':{
#         'Frutta_Secca':9
#     },
#     'SpuntinoPomeriggio':{
#         'Yogurt':125
#     }
# },
# 'Domenica':{

#     'Colazione':{
#     'Succo_di_Frutta':200,
#     'Pane':50,
#     'Prosciutto':40

#     },
#     'Pranzo':{
#     'Filetto':150,
#     'Verdure':200,
#     'Pasta':80,
#     'Frutta':1
#     },
#     'Cena':{
#         'Verdure':200,
#         'Piadine':55,
#         'Salmone':120,
#         'Ortaggi':100,
#         'Frutta':1
#     },
#     'SpuntinoMattina':{
#         'Yogurt':125
#     },
#     'SpuntinoPomeriggio':{
#         'Pane':50,
#         'Pomodori':50
#     }
#     }
# }

emoji_map = {
    "Fagioli": "🫘",
    "Verdure": "🥦",
    "Frutta": "🍎",
    "Piadine": "🌮",
    "Fesa": "🍗",
    "Merluzzo": "🐟",
    "Ortaggi": "🥕",
    "Marmellata": "🍯",
    "Latte": "🥛",
    "Fette Biscottate": "🍞",
    "Frutta Secca": "🥜",
    "Pane": "🍞",
    "Pasta": "🍝",
    "Cereali": "🥣",
    "Farro": "🌾",
    "Pomodori": "🍅",
    "Yogurt": "🍶",
    "Pollo": "🍗",
    "Uova": "🥚",
    "Prosciutto": "🥓",
    "Succo di Frutta": "🧃",
    "Cous Cous": "🍛",
    "Tonno": "🐟",
    "Ricotta": "🧀",
    "Biscotti": "🍪",
    "Patate": "🥔",
    "Filetto": "🥩",
    "Salmone": "🐟"
}

giorni_map = {
    "Monday": "Lunedì",
    "Tuesday": "Martedì",
    "Wednesday": "Mercoledì",
    "Thursday": "Giovedì",
    "Friday": "Venerdì",
    "Saturday": "Sabato",
    "Sunday": "Domenica"
    }
